### ISSUE TITLE
Connecting Through a Firewall

### ISSUE THREAD

**Issue by joesmolsky** [scimma/hop-client#142]
I am using hop-client with the snews-app.  When I try to subscribe or publish from behind a firewall, I get the following error:

%3|1623370289.304|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://kafka.scimma.org:9092/bootstrap]: sasl_ssl://kafka.scimma.org:9092/bootstrap: Connect to ipv4#44.238.143.235:9092 failed: Connection refused (after 0ms in state CONNECT)

Server administration allows for designated global IP addresses to have access to specified ports. I can request port 9092 be opened for connections to 44.238.143.235.

Will this be the only IP address used @bfc5288?

**Comment by cnweaver** [comment]
That's one of three brokers we're operating at the moment:

	$ nslookup kafka.scimma.org
	Server:		2620:fe::fe
	Address:	2620:fe::fe#53
	
	Non-authoritative answer:
	Name:	kafka.scimma.org
	Address: 54.186.11.104
	Name:	kafka.scimma.org
	Address: 44.238.143.235
	Name:	kafka.scimma.org
	Address: 44.236.0.113

However any substantial changes we make to these might result in them moving to other IP addresses owned by AWS, I think, so I doubt it's safe to assume that they will be in the same places long term.
