### ISSUE TITLE
UX: Modify default behavior/name for listening to messages forever

### ISSUE THREAD

**Issue by myNameIsPatrick** [scimma/hop-client#145]
### Description

Currently, to listen to messages from a topic forever, we use the `persist=True/--persist` options for the API/CLI. Since this is typically something someone wants to do, it would be a good idea to change the default so that it is on by default and there's a flag that turns it off to listen up until EOS only.

What should that option be called? Some possible ideas (all with `-e` as the stort option to match kafkacat):

* `--until-eos`
* `--read-until-eos`
* `--stop-at-eos`

### Definition of Done
Two tasks below are completed.

### Tasks/Items:
- [x] Change default to have subscribe listen to messages forever
- [x] Rename option so that it is more explicit what is being done when we only listen to messages until EOS

**Comment by cnweaver** [comment]
My vote would be for `--until-eos`. Including `read` seems redundant, since this would be following the `subscribe` subcommand, so there is already a verb present. 

In terms of matching `kafkacat` (or `kcat` now), wouldn't the short option be `-e`? IIRC it uses `-s` to configure (de)serialization.
