### ISSUE TITLE
compression.codec libzstd error after hop upgrade

### ISSUE THREAD

**Issue by joesmolsky** [scimma/hop-client#193]
I am a hop-client user via snews-pt.  I have been publishing to and subscribing to topics with snews-pt and hop version 0.5.0 and 0.5.1 on two different machines, one Mac and one Linux.

After upgrading to hop 0.7.0, I get the same error message on both machines when I try to publish.  Subscribing does not return the error.  I also get this error if I try to open a writable stream, but not readable.  An example is below.

This code:
```python
from hop import stream
topic = "kafka://kafka.scimma.org/snews.experiments-firedrill"
s = stream.open(topic, "w")
```

Produces this output:
```python
---------------------------------------------------------------------------
KafkaException                            Traceback (most recent call last)
/var/folders/bs/t_j9r03n3h39lmjyz9hr6b540000gn/T/ipykernel_17995/4072266019.py in <cell line: 3>()
      1 from hop import stream
      2 topic = "kafka://kafka.scimma.org/snews.experiments-firedrill"
----> 3 s = stream.open(topic, "w")

~/opt/anaconda3/envs/snews-pt/lib/python3.9/site-packages/hop/io.py in open(self, url, mode, group_id, ignoretest, **kwargs)
    111             if group_id is not None:
    112                 warnings.warn("group ID has no effect when opening a stream in write mode")
--> 113             return Producer(broker_addresses, topics[0], auth=credential, **kwargs)
    114         elif mode == "r":
    115             if group_id is None:

~/opt/anaconda3/envs/snews-pt/lib/python3.9/site-packages/hop/io.py in __init__(self, broker_addresses, topic, **kwargs)
    420         """
    421         logger.info(f"connecting to kafka://{','.join(broker_addresses)}")
--> 422         self._producer = producer.Producer(producer.ProducerConfig(
    423             broker_urls=broker_addresses,
    424             topic=topic,

~/opt/anaconda3/envs/snews-pt/lib/python3.9/site-packages/adc/producer.py in __init__(self, conf)
     27         self.conf = conf
     28         self.logger.debug(f"connecting to producer with config {conf._to_confluent_kafka()}")
---> 29         self._producer = confluent_kafka.Producer(conf._to_confluent_kafka())
     30         # Workaround for https://github.com/edenhill/librdkafka/issues/3871.
     31         # FIXME: Remove once fixed upstream, or on removal of oauth_cb.

KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Unsupported value "zstd" for configuration property "compression.codec": libzstd not available at build time"}
```

On the second machine (Linux), I tested publishing immediately before and after upgrading hop-client from 0.5.0 to 0.7.0.  On the Mac, I have tried going back to other versions of hop-client (0.5.0, 0.5.1, 0.6.0) and I still get the same error.  I have the latest version of librdkafka and libzstd installed.

**Comment by joesmolsky** [comment]
```
❯ hop --version
hop version 0.7.0
```

**Comment by joesmolsky** [comment]
```
❯ hop version
hop-client==0.7.0
adc_streaming==2.2.0
confluent_kafka==1.9.2
librdkafka==1.9.2
```

**Comment by cnweaver** [comment]
Thanks! Of course this reveals a new mystery, which is that adc-streaming 2.2 did not introduce the regrettable new compression default. What happens if you upgrade it to 2.3.0?

**Comment by joesmolsky** [comment]
That worked.  Thanks!  

It is fine on both machines now with adc_streaming 2.3.0 and confluent_kafka 1.9.2.

**Comment by cnweaver** [comment]
Well, that's a head-scratcher. It looks like we may need a patch release of this library, increasing the minimum required version of adc-streaming. I'm glad it's now working for you, and I'll continue to see if I can clean things up so that this doesn't bite anyone else.

**Comment by joesmolsky** [comment]
On the second machine, I also had to update confluent_kafka.  1.7.0 did not work with ads_streaming 2.3.0 and hop-client 0.7.0, but things worked once I upgraded confluence_kafka 1.9.2.
