### ISSUE TITLE
Publish GCN Notices from VOEvent-formatted files

### ISSUE THREAD

**Issue by myNameIsPatrick** [scimma/hop-client#43]
Extend a command-line client to ingest GCN Notices (VOEvents) and post them using VOEvent JSON serialization. Similarly to how `scimma publish` operates, should read in XML files.

Schema: http://www.ivoa.net/documents/Notes/VOEventJSON/20171014/VOEventJSON.pdf

As for possible libraries to leverage, there's https://github.com/timstaley/voevent-parse. VOEventLib and pygcn are both GPL-licensed.

It may make more sense to split up the client into the core client library to just interact with the Kafka broker via scimma (scimma-client) and distinct sources that would ingest packets/files/etc from a variety of methods into the scimma ecosystem. In this case, we could have a library that would just handle GCN notices and leverage pygcn for this. That single library would be GPL licensed but the rest (and the core client) would still be BSD licensed without causing issues.

**Comment by rdt12** [comment]
@myNameIsPatrick I have a very simple gcn reader that outputs JSON in a stand-alone repository:

https://github.com/scimma/gcn2stdout

I'm working on another program named voevent2scimma that will read input from gcn2stdout (or any other program that outputs VOEvents in  a specified format) and publish to scimma. I plan for it to take the program to use to get VOEvent messages as a configuration parameter. It will import the scimma client library and use it to interact with the scimma server.

I have a question about the format of input messages to the scimma client. Should the client accept XML and do the parsing or should it take JSON (if so, what format)?
Currently, gcn2stdout outputs JSON, but it would be easy to make it output raw XML.

**Comment by myNameIsPatrick** [comment]
@rdt12, that URL returns a 404 error for me, I may not be a member of that repo if it's private.

That plan sounds reasonable to me. I'd rather the client accept JSON with the schema defined in the URL in the first comment. I see slight differences in the schema just due to how XML can have duplicate keys, but it should almost be one-to-one.

I have started work on the schemas for VOEvents and Circulars, as a way to more finely control the data products we support. The VOEvent data class is here: https://github.com/scimma/client_library/blob/master/scimma/client/models.py#L11. As long as the JSON packet is read in via `json.loads` or similar, you should be able to unpack it into the data structure by doing:

```
from scimma.client import models

msg = json.loads(msg_json)
voevent = models.VOEvent(**msg)
```

and then to send it to the client, you can serialize it like:

```
packet = json.dumps(voevent.todict())
```

Right now it's a bit of boilerplate for not much gain, but I could imagine defining methods which give some value to the structures, like client-side validation, serialization, etc. Currently what it does give you are structures with pre-defined defaults and will complain if the data you're trying to pass in is malformed in some way.

**Comment by rdt12** [comment]
@myNameIsPatrick You should have access to the repo now.
