### ISSUE TITLE
Rename repository + description

### ISSUE THREAD

**Issue by myNameIsPatrick** [scimma/hop-client#50]
Following the server convention, I think it would be more suited to name the repository `scimma-client` to match the package as well. The project description should be renamed to reflect what the codebase is meant for, possibly something like "a pub-sub client library for Multimessenger Astrophysics"

**Comment by mjuric** [comment]
After discussing this today, I'd propose to go with `hop` for the name of the repository (to match the cmdine tool name, and package name).
