### ISSUE TITLE
Message delivery certainty/ error reporting

### ISSUE THREAD

**Issue by rdt12** [scimma/hop-client#63]
Story: As a developer using the the hop library, I would like to know that when I call write on a stream either I get an error or the message was actually received by the kafka server.

Some things that should cause an error:

- [x] Stream.open: name of server cannot be resolved
- [x]  Stream.open: a connection to the server:port could not be established
- [x]  Stream.open returns a AlertBroker object. Calling write on that seems to fail silently if Stream.open is given an invalid name. Maybe Stream.open should return a wrapper object that does some sanity checking.

It's possible that I should be using some aspect of the AlertBroker object to do error checking. However, I think that the story still stands and this error checking should be in the hop client library.

**Comment by spenczar** [comment]
These were fixed in #69 / [adc-streaming #32](https://github.com/astronomy-commons/adc-streaming/pull/32).
