### ISSUE TITLE
In subscribe, run a callback instead of printing the message.

### ISSUE THREAD

**Issue by rdt12** [scimma/hop-client#83]
### Description
As a developer, I would like to use the scaffolding provided by the subscribe module and run my own code instead of printing the message.

There are a number of ways to accomplish this. Here are two examples::

   1. factor the code out of _main into a new function, say `guts`, and have `_main` and a new function named, say `subscribe` call `guts` with a callback function.  `_main` could use `print_message` as the callback

  2. Add a callback argument to `_main` that defaults to `print_message`.

### Definition of Done

A test program is written that defines a callback and ensures that the callback is called.

**Comment by myNameIsPatrick** [comment]
@rdt12, just wanted to check in to see if you think there's still value in doing something like this after #82, which drastically simplified the subscribe main code (https://github.com/scimma/hop-client/blob/master/hop/subscribe.py#L49-L59).

**Comment by rdt12** [comment]
@myNameIsPatrick I guess I haven't looked at the code since July. It looks like most of the details are now buried in the  io.Stream class so I agree that there is no point to this and it can be closed.

**Comment by rdt12** [comment]
Based on my last comment, closing this issue.
