### ISSUE TITLE
UX: Support message format plugins

### ISSUE THREAD

**Issue by spenczar** [scimma/hop-client#84]
### Description
As a developer, I want to add my own message formats through plugins.

We have message formats, and we support a small set of them. But letting users add more through pip-installable plugins would be really great.

See discussion in https://github.com/scimma/hop-client/pull/82/files#r447343536; pluggy might be a good approach here.

### Definition of Done
Have an external package which provides a demonstration plugin, adding support for some new message format. It can be a test format, or it could be something real, like LSST alerts.

**Comment by myNameIsPatrick** [comment]
Was playing around with this for another project and have convinced myself that using pluggy would be definitely doable and would work nicely with the client.
